# Makefile for the Ubuntu platform

TARGET := bin/vim_ubuntu
BUILD_DIR := build/ubuntu
CC := gcc
LD := gcc

# Source files
CORE_SRCS := $(wildcard src/core/*.c) $(wildcard src/core/lib/*.c)
PLATFORM_SRCS := src/platform/ubuntu/platform_ubuntu.c src/platform/cbm/kernal.c
SRCS := $(CORE_SRCS) $(PLATFORM_SRCS)

OBJS := $(patsubst %.c,$(BUILD_DIR)/%.o,$(SRCS))

# Compiler and Linker flags
CFLAGS := -g -Isrc -Isrc/core -Isrc/platform -Isrc/platform/cbm -D__UBUNTU__ -DDEBUG_ON
CFLAGS += -Wshadow -Wcast-align -Wunused -Wnull-dereference -Wformat=2 -Wimplicit-fallthrough
CFLAGS += -Wno-incompatible-pointer-types-discards-qualifiers -Wno-sign-conversion -Wno-int-conversion -Wno-pointer-sign
LDFLAGS := -lncurses

# Default target
all: $(TARGET)

$(TARGET): $(OBJS)
	@mkdir -p bin
	$(LD) -o $(TARGET) $(OBJS) $(LDFLAGS)
	@echo "Build complete: $(TARGET)"

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD_DIR) $(TARGET)

.PHONY: all clean
