#ifndef KEYCODES_H
#define KEYCODES_H

typedef enum {
    // Special Keys
    VIM_KEY_NULL = 0,
    VIM_KEY_CTRL_A = 1,
    VIM_KEY_CTRL_B = 2,
    VIM_KEY_CTRL_C = 3,
    VIM_KEY_CTRL_D = 4,
    VIM_KEY_CTRL_E = 5,
    VIM_KEY_CTRL_F = 6,
    VIM_KEY_CTRL_G = 7,
    VIM_KEY_CTRL_H = 8,
    VIM_KEY_CTRL_I = 9,
    VIM_KEY_LF = 10,
    VIM_KEY_CTRL_K = 11,
    VIM_KEY_CTRL_L = 12,
    VIM_KEY_CR = 13,
    VIM_KEY_CTRL_N = 14,
    VIM_KEY_CTRL_O = 15,
    VIM_KEY_CTRL_P = 16,
    VIM_KEY_CTRL_Q = 17,
    VIM_KEY_CTRL_R = 18,
    VIM_KEY_CTRL_S = 19,
    VIM_KEY_BACKSPACE = 20,
    VIM_KEY_CTRL_U = 21,
    VIM_KEY_CTRL_V = 22,
    VIM_KEY_CTRL_W = 23,
    VIM_KEY_CTRL_X = 24,
    VIM_KEY_CTRL_Y = 25,
    VIM_KEY_CTRL_Z = 26,
    VIM_KEY_ESC = 27,

    // Printable ASCII
    VIM_KEY_SPACE = 32,
    VIM_KEY_EXCLAMATION,
    VIM_KEY_QUOTES,
    VIM_KEY_HASH,
    VIM_KEY_DOLLAR,
    VIM_KEY_PERCENT,
    VIM_KEY_AMPERSAND,
    VIM_KEY_APOSTROPHE,
    VIM_KEY_PAREN_LEFT,
    VIM_KEY_PAREN_RIGHT,
    VIM_KEY_ASTERISK,
    VIM_KEY_PLUS,
    VIM_KEY_COMMA,
    VIM_KEY_MINUS,
    VIM_KEY_PERIOD,
    VIM_KEY_SLASH,
    VIM_KEY_0, VIM_KEY_1, VIM_KEY_2, VIM_KEY_3, VIM_KEY_4, VIM_KEY_5, VIM_KEY_6, VIM_KEY_7, VIM_KEY_8, VIM_KEY_9,
    VIM_KEY_COLON,
    VIM_KEY_SEMICOLON,
    VIM_KEY_LESS_THAN,
    VIM_KEY_EQUAL,
    VIM_KEY_GREATER_THAN,
    VIM_KEY_QUESTION,
    VIM_KEY_AT,

    // Uppercase Letters
    VIM_KEY_A_UPPER, VIM_KEY_B_UPPER, VIM_KEY_C_UPPER, VIM_KEY_D_UPPER, VIM_KEY_E_UPPER, VIM_KEY_F_UPPER, VIM_KEY_G_UPPER,
    VIM_KEY_H_UPPER, VIM_KEY_I_UPPER, VIM_KEY_J_UPPER, VIM_KEY_K_UPPER, VIM_KEY_L_UPPER, VIM_KEY_M_UPPER, VIM_KEY_N_UPPER,
    VIM_KEY_O_UPPER, VIM_KEY_P_UPPER, VIM_KEY_Q_UPPER, VIM_KEY_R_UPPER, VIM_KEY_S_UPPER, VIM_KEY_T_UPPER, VIM_KEY_U_UPPER,
    VIM_KEY_V_UPPER, VIM_KEY_W_UPPER, VIM_KEY_X_UPPER, VIM_KEY_Y_UPPER, VIM_KEY_Z_UPPER,

    VIM_KEY_BRACKET_LEFT,
    VIM_KEY_BACKSLASH,
    VIM_KEY_BRACKET_RIGHT,
    VIM_KEY_CARET,
    VIM_KEY_UNDERSCORE,
    VIM_KEY_GRAVE,

    // Lowercase Letters
    VIM_KEY_A_LOWER, VIM_KEY_B_LOWER, VIM_KEY_C_LOWER, VIM_KEY_D_LOWER, VIM_KEY_E_LOWER, VIM_KEY_F_LOWER, VIM_KEY_G_LOWER,
    VIM_KEY_H_LOWER, VIM_KEY_I_LOWER, VIM_KEY_J_LOWER, VIM_KEY_K_LOWER, VIM_KEY_L_LOWER, VIM_KEY_M_LOWER, VIM_KEY_N_LOWER,
    VIM_KEY_O_LOWER, VIM_KEY_P_LOWER, VIM_KEY_Q_LOWER, VIM_KEY_R_LOWER, VIM_KEY_S_LOWER, VIM_KEY_T_LOWER, VIM_KEY_U_LOWER,
    VIM_KEY_V_LOWER, VIM_KEY_W_LOWER, VIM_KEY_X_LOWER, VIM_KEY_Y_LOWER, VIM_KEY_Z_LOWER,

    VIM_KEY_BRACE_LEFT,
    VIM_KEY_PIPE,
    VIM_KEY_BRACE_RIGHT,
    VIM_KEY_TILDE,

    // CBM Specific Keys
    VIM_KEY_DOWN = 17,
    VIM_KEY_RIGHT = 29,
    VIM_KEY_UP = 145,
    VIM_KEY_LEFT = 157,
    VIM_KEY_HOME = 19,
    VIM_KEY_CLR = 147,
    VIM_KEY_SHIFT_HOME = 147,

    // Help key (Mega65)
    VIM_KEY_HELP = 132,

} eVimKeyCode;

#endif // KEYCODES_H
