#ifndef PLATFORM_C64_H
#define PLATFORM_C64_H

#include "../core/globals.h"

#define PLATFORM_FILENAME_COL 10

#define PLATFORM_MODE_NORMAL_STR "*N*"
#define PLATFORM_MODE_INSERT_STR "*I*"
#define PLATFORM_WELCOME_STRING "vIM3 eDITOR - " VERSION_STRING

#endif // PLATFORM_C64_H